Google pay
Cattari/react-native-adyen-drop-in pull request #9
Opened 2023-02-28 15:31 UTC by SRyzhykh

2023-02-28 16:11 UTC, daklin2 commented on android/src/main/java/com/reactnative/adyendropin/AdyenDropInPayment.java
> +                .build();
MerchantAccount should be dynamic, not a hard-coded string.

2023-02-28 16:13 UTC, daklin2 commented on android/src/main/java/com/reactnative/adyendropin/AdyenDropInPayment.java
> +                .build();
Why you hard-coding env for payments? Is it always gonna be test? How we plan to dynamically support production one?

2023-02-28 16:14 UTC, daklin2 requested changes
Please consider changes according to the comments

2023-03-02 11:38 UTC, daklin2 approved these changes

2023-03-02 12:55 UTC, Cattari approved these changes

2023-03-02 12:55 UTC, merged